In [1]:
# Reading Tabular Data into DataFrames


import pandas as pd # pd is an alias

data = pd.read_csv("data/gapminder_gdp_oceania.csv")
print(data)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686
1  New Zealand     10556.57566     12247.39532     13175.67800

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928
1     14463.91893     16046.03728     16233.71770     17632.41040

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473
1     19007.19129     18363.32494     21050.41377     23189.80135

   gdpPercap_2007
0     34435.36744
1     25185.00911

In [2]:
data # this prints out the data we made above - it looks better with just data

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Australia,10039.59564,10949.64959,12217.22686,14526.12465,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
1,New Zealand,10556.57566,12247.39532,13175.67800,14463.91893,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

In [5]:
# Using "index_col"


data = pd.read_csv("data/gapminder_gdp_oceania.csv",index_col="country")
print(data)

             gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country
Australia       10039.59564     10949.64959     12217.22686     14526.12465
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Australia       16788.62948     18334.19751     19477.00928     21888.88903
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Australia       23424.76683     26997.93657     30687.75473     34435.36744
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gdpPercap_1952  2 non-null      float64
 1   gdpPercap_1957  2 non-null      float64
 2   gdpPercap_1962  2 non-null      float64
 3   gdpPercap_1967  2 non-null      float64
 4   gdpPercap_1972  2 non-null      float64
 5   gdpPercap_1977  2 non-null      float64
 6   gdpPercap_1982  2 non-null      float64
 7   gdpPercap_1987  2 non-null      float64
 8   gdpPercap_1992  2 non-null      float64
 9   gdpPercap_1997  2 non-null      float64
 10  gdpPercap_2002  2 non-null      float64
 11  gdpPercap_2007  2 non-null      float64
dtypes: float64(12)
memory usage: 208.0+ bytes

In [7]:
print(data.columns) # shows all the columns that are available

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [3]:
print(data.T) # this means "transpose" (switched the row and columns around

                          0            1
country           Australia  New Zealand
gdpPercap_1952  10039.59564  10556.57566
gdpPercap_1957  10949.64959  12247.39532
gdpPercap_1962  12217.22686    13175.678
gdpPercap_1967  14526.12465  14463.91893
gdpPercap_1972  16788.62948  16046.03728
gdpPercap_1977  18334.19751   16233.7177
gdpPercap_1982  19477.00928   17632.4104
gdpPercap_1987  21888.88903  19007.19129
gdpPercap_1992  23424.76683  18363.32494
gdpPercap_1997  26997.93657  21050.41377
gdpPercap_2002  30687.75473  23189.80135
gdpPercap_2007  34435.36744  25185.00911

In [9]:
print(data.describe)

<bound method NDFrame.describe of              gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country
Australia       10039.59564     10949.64959     12217.22686     14526.12465
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country
Australia       16788.62948     18334.19751     19477.00928     21888.88903
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Australia       23424.76683     26997.93657     30687.75473     34435.36744
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911  >

In [10]:
americas = pd.read_csv("data/gapminder_gdp_americas.csv", index_col="country")

In [11]:
americas.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,4079.062552,4616.043733,4901.541870,5668.253496,6491.334139,7352.007126,7506.737088,7793.400261,8044.934406,8889.300863,9287.677107,11003.031625
std,3001.727522,3312.381083,3421.740569,4160.885560,4754.404329,5355.602518,5530.490471,6665.039509,7047.089191,7874.225145,8895.817785,9713.209302
min,1397.717137,1544.402995,1662.137359,1452.057666,1654.456946,1874.298931,2011.159549,1823.015995,1456.309517,1341.726931,1270.364932,1201.637154
25%,2428.237769,2487.365989,2750.364446,3242.531147,4031.408271,4756.763836,4258.503604,4140.442097,4439.450840,4684.313807,4858.347495,5728.353514
50%,3048.302900,3780.546651,4086.114078,4643.393534,5305.445256,6281.290855,6434.501797,6360.943444,6618.743050,7113.692252,6994.774861,8948.102923
75%,3939.978789,4756.525781,5180.755910,5788.093330,6809.406690,7674.929108,8997.897412,7807.095818,8137.004775,9767.297530,8797.640716,11977.574960
max,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.653090

In [12]:
help(americas.head)

Help on method head in module pandas.core.generic:

head(n: 'int' = 5) -> 'FrameOrSeries' method of pandas.core.frame.DataFrame instance
    Return the first `n` rows.

    This function returns the first `n` rows for the object based
    on position. It is useful for quickly testing if your object
    has the right type of data in it.

    For negative values of `n`, this function returns all rows except
    the last `n` rows, equivalent to ``df[:-n]``.

    Parameters
    ----------
    n : int, default 5
        Number of rows to select.

    Returns
    -------
    same type as caller
        The first `n` rows of the caller object.

    See Also
    --------
    DataFrame.tail: Returns the last `n` rows.

    Examples
    --------
    >>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
    ...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
    >>> df
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot
    6      shark
    7      whale
    8      zebra

    Viewing the first 5 lines

    >>> df.head()
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey

    Viewing the first `n` lines (three in this case)

    >>> df.head(3)
          animal
    0  alligator
    1        bee
    2     falcon

    For negative values of `n`

    >>> df.head(-3)
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot

In [13]:
print(americas.tail(5))

                    continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Puerto Rico          Americas     3081.959785     3907.156189     5108.344630
Trinidad and Tobago  Americas     3023.271928     4100.393400     4997.523971
United States        Americas    13990.482080    14847.127120    16173.145860
Uruguay              Americas     5716.766744     6150.772969     5603.357717
Venezuela            Americas     7689.799761     9802.466526     8422.974165

                     gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Puerto Rico             6929.277714     9123.041742     9770.524921
Trinidad and Tobago     5621.368472     6619.551419     7899.554209
United States          19530.365570    21806.035940    24072.632130
Uruguay                 5444.619620     5703.408898     6504.339663
Venezuela               9541.474188    10505.259660    13143.950950

                     gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Puerto Rico            10330.989150    12281.341910    14641.587110
Trinidad and Tobago     9119.528607     7388.597823     7370.990932
United States          25009.559140    29884.350410    32003.932240
Uruguay                 6920.223051     7452.398969     8137.004775
Venezuela              11152.410110     9883.584648    10733.926310

                     gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Puerto Rico            16999.433300    18855.606180     19328.70901
Trinidad and Tobago     8792.573126    11460.600230     18008.50924
United States          35767.433030    39097.099550     42951.65309
Uruguay                 9230.240708     7727.002004     10611.46299
Venezuela              10165.495180     8605.047831     11415.80569

In [14]:
print(americas.head(5))

          continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Argentina  Americas     5911.315053     6856.856212     7133.166023
Bolivia    Americas     2677.326347     2127.686326     2180.972546
Brazil     Americas     2108.944355     2487.365989     3336.585802
Canada     Americas    11367.161120    12489.950060    13462.485550
Chile      Americas     3939.978789     4315.622723     4519.094331

           gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
country
Argentina     8052.953021     9443.038526    10079.026740     8997.897412
Bolivia       2586.886053     2980.331339     3548.097832     3156.510452
Brazil        3429.864357     4985.711467     6660.118654     7030.835878
Canada       16076.588030    18970.570860    22090.883060    22898.792140
Chile         5106.654313     5494.024437     4756.763836     5095.665738

           gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
country
Argentina     9139.671389     9308.418710    10967.281950     8797.640716
Bolivia       2753.691490     2961.699694     3326.143191     3413.262690
Brazil        7807.095818     6950.283021     7957.980824     8131.212843
Canada       26626.515030    26342.884260    28954.925890    33328.965070
Chile         5547.063754     7596.125964    10118.053180    10778.783850

           gdpPercap_2007
country
Argentina    12779.379640
Bolivia       3822.137084
Brazil        9065.800825
Canada       36319.235010
Chile        13171.638850

In [15]:
# specify the "n mumber" as in n=3
print(americas.head(n=3))

          continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Argentina  Americas     5911.315053     6856.856212     7133.166023
Bolivia    Americas     2677.326347     2127.686326     2180.972546
Brazil     Americas     2108.944355     2487.365989     3336.585802

           gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
country
Argentina     8052.953021     9443.038526    10079.026740     8997.897412
Bolivia       2586.886053     2980.331339     3548.097832     3156.510452
Brazil        3429.864357     4985.711467     6660.118654     7030.835878

           gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
country
Argentina     9139.671389     9308.418710    10967.281950     8797.640716
Bolivia       2753.691490     2961.699694     3326.143191     3413.262690
Brazil        7807.095818     6950.283021     7957.980824     8131.212843

           gdpPercap_2007
country
Argentina    12779.379640
Bolivia       3822.137084
Brazil        9065.800825

In [16]:
# the .T means "transform" swap rows and columns about (the "view" not the actual data) 
americas_flipped = americas.T

In [17]:
print(americas_flipped.head(3))

country           Argentina      Bolivia       Brazil       Canada  \
continent          Americas     Americas     Americas     Americas
gdpPercap_1952  5911.315053  2677.326347  2108.944355  11367.16112
gdpPercap_1957  6856.856212  2127.686326  2487.365989  12489.95006

country               Chile     Colombia   Costa Rica         Cuba  \
continent          Americas     Americas     Americas     Americas
gdpPercap_1952  3939.978789  2144.115096  2627.009471   5586.53878
gdpPercap_1957  4315.622723  2323.805581  2990.010802  6092.174359

country        Dominican Republic      Ecuador  ...       Mexico    Nicaragua  \
continent                Americas     Americas  ...     Americas     Americas
gdpPercap_1952        1397.717137  3522.110717  ...  3478.125529  3112.363948
gdpPercap_1957        1544.402995  3780.546651  ...  4131.546641  3457.415947

country              Panama     Paraguay         Peru  Puerto Rico  \
continent          Americas     Americas     Americas     Americas
gdpPercap_1952  2480.380334  1952.308701  3758.523437  3081.959785
gdpPercap_1957  2961.800905  2046.154706  4245.256698  3907.156189

country        Trinidad and Tobago United States      Uruguay    Venezuela
continent                 Americas      Americas     Americas     Americas
gdpPercap_1952         3023.271928   13990.48208  5716.766744  7689.799761
gdpPercap_1957           4100.3934   14847.12712  6150.772969  9802.466526

[3 rows x 25 columns]

In [18]:
print(americas_flipped.describe())

country Argentina   Bolivia    Brazil    Canada     Chile  Colombia  \
count          13        13        13        13        13        13
unique         13        13        13        13        13        13
top      Americas  Americas  Americas  Americas  Americas  Americas
freq            1         1         1         1         1         1

country Costa Rica      Cuba Dominican Republic   Ecuador  ...    Mexico  \
count           13        13                 13        13  ...        13
unique          13        13                 13        13  ...        13
top       Americas  Americas           Americas  Americas  ...  Americas
freq             1         1                  1         1  ...         1

country Nicaragua    Panama  Paraguay      Peru Puerto Rico  \
count          13        13        13        13          13
unique         13        13        13        13          13
top      Americas  Americas  Americas  Americas    Americas
freq            1         1         1         1           1

country Trinidad and Tobago United States   Uruguay Venezuela
count                    13            13        13        13
unique                   13            13        13        13
top                Americas      Americas  Americas  Americas
freq                      1             1         1         1

[4 rows x 25 columns]

In [19]:
americas_flipped.tail(n=3).T

                    gdpPercap_1997 gdpPercap_2002 gdpPercap_2007
country
Argentina              10967.28195    8797.640716    12779.37964
Bolivia                3326.143191     3413.26269    3822.137084
Brazil                 7957.980824    8131.212843    9065.800825
Canada                 28954.92589    33328.96507    36319.23501
Chile                  10118.05318    10778.78385    13171.63885
Colombia               6117.361746    5755.259962    7006.580419
Costa Rica             6677.045314    7723.447195     9645.06142
Cuba                   5431.990415    6340.646683    8948.102923
Dominican Republic     3614.101285    4563.808154    6025.374752
Ecuador                7429.455877    5773.044512    6873.262326
El Salvador            5154.825496    5351.568666    5728.353514
Guatemala              4684.313807    4858.347495    5186.050003
Haiti                  1341.726931    1270.364932    1201.637154
Honduras               3160.454906     3099.72866    3548.330846
Jamaica                7121.924704    6994.774861    7320.880262
Mexico                  9767.29753    10742.44053    11977.57496
Nicaragua              2253.023004    2474.548819    2749.320965
Panama                 7113.692252    7356.031934    9809.185636
Paraguay               4247.400261    3783.674243    4172.838464
Peru                   5838.347657    5909.020073    7408.905561
Puerto Rico             16999.4333    18855.60618    19328.70901
Trinidad and Tobago    8792.573126    11460.60023    18008.50924
United States          35767.43303    39097.09955    42951.65309
Uruguay                9230.240708    7727.002004    10611.46299
Venezuela              10165.49518    8605.047831    11415.80569

In [20]:
# we could chain all these operations together, like bash commands.

americas.T.tail(n=3).T

                    gdpPercap_1997 gdpPercap_2002 gdpPercap_2007
country
Argentina              10967.28195    8797.640716    12779.37964
Bolivia                3326.143191     3413.26269    3822.137084
Brazil                 7957.980824    8131.212843    9065.800825
Canada                 28954.92589    33328.96507    36319.23501
Chile                  10118.05318    10778.78385    13171.63885
Colombia               6117.361746    5755.259962    7006.580419
Costa Rica             6677.045314    7723.447195     9645.06142
Cuba                   5431.990415    6340.646683    8948.102923
Dominican Republic     3614.101285    4563.808154    6025.374752
Ecuador                7429.455877    5773.044512    6873.262326
El Salvador            5154.825496    5351.568666    5728.353514
Guatemala              4684.313807    4858.347495    5186.050003
Haiti                  1341.726931    1270.364932    1201.637154
Honduras               3160.454906     3099.72866    3548.330846
Jamaica                7121.924704    6994.774861    7320.880262
Mexico                  9767.29753    10742.44053    11977.57496
Nicaragua              2253.023004    2474.548819    2749.320965
Panama                 7113.692252    7356.031934    9809.185636
Paraguay               4247.400261    3783.674243    4172.838464
Peru                   5838.347657    5909.020073    7408.905561
Puerto Rico             16999.4333    18855.60618    19328.70901
Trinidad and Tobago    8792.573126    11460.60023    18008.50924
United States          35767.43303    39097.09955    42951.65309
Uruguay                9230.240708    7727.002004    10611.46299
Venezuela              10165.49518    8605.047831    11415.80569

In [21]:
# To print out to a new csv file, using the ".to_csv" method

americas.to_csv("processed.csv")

In [22]:
# you can't do the help, unless you specify the dataframe as well(in this case americas)

help(americas.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(path_or_buf: 'FilePathOrBuffer[AnyStr] | None' = None, sep: 'str' = ',', na_rep: 'str' = '', float_format: 'str | None' = None, columns: 'Sequence[Hashable] | None' = None, header: 'bool_t | list[str]' = True, index: 'bool_t' = True, index_label: 'IndexLabel | None' = None, mode: 'str' = 'w', encoding: 'str | None' = None, compression: 'CompressionOptions' = 'infer', quoting: 'int | None' = None, quotechar: 'str' = '"', line_terminator: 'str | None' = None, chunksize: 'int | None' = None, date_format: 'str | None' = None, doublequote: 'bool_t' = True, escapechar: 'str | None' = None, decimal: 'str' = '.', errors: 'str' = 'strict', storage_options: 'StorageOptions' = None) -> 'str | None' method of pandas.core.frame.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.  If a non-binary file object is passed, it should be opened
        with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.

        .. versionchanged:: 1.2.0

           Support for binary file objects was introduced.

    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, default None
        Format string for floating point numbers.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : str
        Python write mode, default 'w'.
    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.
    compression : str or dict, default 'infer'
        If str, represents compression mode. If dict, value at 'method' is
        the compression mode. Compression mode may be any of the following
        possible values: {'infer', 'gzip', 'bz2', 'zip', 'xz', None}. If
        compression mode is 'infer' and `path_or_buf` is path-like, then
        detect compression mode from the following extensions: '.gz',
        '.bz2', '.zip' or '.xz'. (otherwise no compression). If dict given
        and mode is one of {'zip', 'gzip', 'bz2'}, or inferred as
        one of the above, other entries passed as
        additional compression options.

        .. versionchanged:: 1.0.0

           May now be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

        .. versionchanged:: 1.1.0

           Passing compression options as keys in dict is
           supported for compression modes 'gzip' and 'bz2'
           as well as 'zip'.

        .. versionchanged:: 1.2.0

            Compression is supported for binary file objects.

        .. versionchanged:: 1.2.0

            Previous versions forwarded dict entries for 'gzip' to
            `gzip.open` instead of `gzip.GzipFile` which prevented
            setting `mtime`.

    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    line_terminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

        .. versionadded:: 1.1.0

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib`` as header options. For other URLs (e.g.
        starting with "s3://", and "gcs://") the key-value pairs are forwarded to
        ``fsspec``. Please see ``fsspec`` and ``urllib`` for more details.

        .. versionadded:: 1.2.0

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
    ...                    'mask': ['red', 'purple'],
    ...                    'weapon': ['sai', 'bo staff']})
    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'

    Create 'out.zip' containing 'out.csv'

    >>> compression_opts = dict(method='zip',
    ...                         archive_name='out.csv')  # doctest: +SKIP
    >>> df.to_csv('out.zip', index=False,
    ...           compression=compression_opts)  # doctest: +SKIP

In [23]:
# here we are using "numerical position" for both "row" and "column" using "iloc"
import pandas as pd
data = pd.read_csv("data/gapminder_gdp_europe.csv", index_col="country")
print(data.iloc[0,0]) # "position"[0,0] is first row (0), first column (0)

1601.056136

In [24]:
# this is what the data looks like. here we can see Albania is first row (row zero)
import pandas as pd
data = pd.read_csv("data/gapminder_gdp_europe.csv", index_col="country")
print(data)

                        gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Albania                    1601.056136     1942.284244     2312.888958
Austria                    6137.076492     8842.598030    10750.721110
Belgium                    8343.105127     9714.960623    10991.206760
Bosnia and Herzegovina      973.533195     1353.989176     1709.683679
Bulgaria                   2444.286648     3008.670727     4254.337839
Croatia                    3119.236520     4338.231617     5477.890018
Czech Republic             6876.140250     8256.343918    10136.867130
Denmark                    9692.385245    11099.659350    13583.313510
Finland                    6424.519071     7545.415386     9371.842561
France                     7029.809327     8662.834898    10560.485530
Germany                    7144.114393    10187.826650    12902.462910
Greece                     3530.690067     4916.299889     6017.190733
Hungary                    5263.673816     6040.180011     7550.359877
Iceland                    7267.688428     9244.001412    10350.159060
Ireland                    5210.280328     5599.077872     6631.597314
Italy                      4931.404155     6248.656232     8243.582340
Montenegro                 2647.585601     3682.259903     4649.593785
Netherlands                8941.571858    11276.193440    12790.849560
Norway                    10095.421720    11653.973040    13450.401510
Poland                     4029.329699     4734.253019     5338.752143
Portugal                   3068.319867     3774.571743     4727.954889
Romania                    3144.613186     3943.370225     4734.997586
Serbia                     3581.459448     4981.090891     6289.629157
Slovak Republic            5074.659104     6093.262980     7481.107598
Slovenia                   4215.041741     5862.276629     7402.303395
Spain                      3834.034742     4564.802410     5693.843879
Sweden                     8527.844662     9911.878226    12329.441920
Switzerland               14734.232750    17909.489730    20431.092700
Turkey                     1969.100980     2218.754257     2322.869908
United Kingdom             9979.508487    11283.177950    12477.177070

                        gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Albania                    2760.196931     3313.422188     3533.003910
Austria                   12834.602400    16661.625600    19749.422300
Belgium                   13149.041190    16672.143560    19117.974480
Bosnia and Herzegovina     2172.352423     2860.169750     3528.481305
Bulgaria                   5577.002800     6597.494398     7612.240438
Croatia                    6960.297861     9164.090127    11305.385170
Czech Republic            11399.444890    13108.453600    14800.160620
Denmark                   15937.211230    18866.207210    20422.901500
Finland                   10921.636260    14358.875900    15605.422830
France                    12999.917660    16107.191710    18292.635140
Germany                   14745.625610    18016.180270    20512.921230
Greece                     8513.097016    12724.829570    14195.524280
Hungary                    9326.644670    10168.656110    11674.837370
Iceland                   13319.895680    15798.063620    19654.962470
Ireland                    7655.568963     9530.772896    11150.981130
Italy                     10022.401310    12269.273780    14255.984750
Montenegro                 5907.850937     7778.414017     9595.929905
Netherlands               15363.251360    18794.745670    21209.059200
Norway                    16361.876470    18965.055510    23311.349390
Poland                     6557.152776     8006.506993     9508.141454
Portugal                   6361.517993     9022.247417    10172.485720
Romania                    6470.866545     8011.414402     9356.397240
Serbia                     7991.707066    10522.067490    12980.669560
Slovak Republic            8412.902397     9674.167626    10922.664040
Slovenia                   9405.489397    12383.486200    15277.030170
Spain                      7993.512294    10638.751310    13236.921170
Sweden                    15258.296970    17832.024640    18855.725210
Switzerland               22966.144320    27195.113040    26982.290520
Turkey                     2826.356387     3450.696380     4269.122326
United Kingdom            14142.850890    15895.116410    17428.748460

                        gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Albania                    3630.880722     3738.932735     2497.437901
Austria                   21597.083620    23687.826070    27042.018680
Belgium                   20979.845890    22525.563080    25575.570690
Bosnia and Herzegovina     4126.613157     4314.114757     2546.781445
Bulgaria                   8224.191647     8239.854824     6302.623438
Croatia                   13221.821840    13822.583940     8447.794873
Czech Republic            15377.228550    16310.443400    14297.021220
Denmark                   21688.040480    25116.175810    26406.739850
Finland                   18533.157610    21141.012230    20647.164990
France                    20293.897460    22066.442140    24703.796150
Germany                   22031.532740    24639.185660    26505.303170
Greece                    15268.420890    16120.528390    17541.496340
Hungary                   12545.990660    12986.479980    10535.628550
Iceland                   23269.607500    26923.206280    25144.392010
Ireland                   12618.321410    13872.866520    17558.815550
Italy                     16537.483500    19207.234820    22013.644860
Montenegro                11222.587620    11732.510170     7003.339037
Netherlands               21399.460460    23651.323610    26790.949610
Norway                    26298.635310    31540.974800    33965.661150
Poland                     8451.531004     9082.351172     7738.881247
Portugal                  11753.842910    13039.308760    16207.266630
Romania                    9605.314053     9696.273295     6598.409903
Serbia                    15181.092700    15870.878510     9325.068238
Slovak Republic           11348.545850    12037.267580     9498.467723
Slovenia                  17866.721750    18678.534920    14214.716810
Spain                     13926.169970    15764.983130    18603.064520
Sweden                    20667.381250    23586.929270    23880.016830
Switzerland               28397.715120    30281.704590    31871.530300
Turkey                     4241.356344     5089.043686     5678.348271
United Kingdom            18232.424520    21664.787670    22705.092540

                        gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Albania                    3193.054604     4604.211737     5937.029526
Austria                   29095.920660    32417.607690    36126.492700
Belgium                   27561.196630    30485.883750    33692.605080
Bosnia and Herzegovina     4766.355904     6018.975239     7446.298803
Bulgaria                   5970.388760     7696.777725    10680.792820
Croatia                    9875.604515    11628.388950    14619.222720
Czech Republic            16048.514240    17596.210220    22833.308510
Denmark                   29804.345670    32166.500060    35278.418740
Finland                   23723.950200    28204.590570    33207.084400
France                    25889.784870    28926.032340    30470.016700
Germany                   27788.884160    30035.801980    32170.374420
Greece                    18747.698140    22514.254800    27538.411880
Hungary                   11712.776800    14843.935560    18008.944440
Iceland                   28061.099660    31163.201960    36180.789190
Ireland                   24521.947130    34077.049390    40675.996350
Italy                     24675.024460    27968.098170    28569.719700
Montenegro                 6465.613349     6557.194282     9253.896111
Netherlands               30246.130630    33724.757780    36797.933320
Norway                    41283.164330    44683.975250    49357.190170
Poland                    10159.583680    12002.239080    15389.924680
Portugal                  17641.031560    19970.907870    20509.647770
Romania                    7346.547557     7885.360081    10808.475610
Serbia                     7914.320304     7236.075251     9786.534714
Slovak Republic           12126.230650    13638.778370    18678.314350
Slovenia                  17161.107350    20660.019360    25768.257590
Spain                     20445.298960    24835.471660    28821.063700
Sweden                    25266.594990    29341.630930    33859.748350
Switzerland               32135.323010    34480.957710    37506.419070
Turkey                     6601.429915     6508.085718     8458.276384
United Kingdom            26074.531360    29478.999190    33203.261280

In [25]:
print(data.loc["Albania", "gdpPercap_1952"])

1601.056136

In [26]:
# to print only the one "row" for "Albania", 
# but print it for every column label 1952 -> 2007
# Similar syntax to "slicing a word string".

print(data.loc["Albania", :])

gdpPercap_1952    1601.056136
gdpPercap_1957    1942.284244
gdpPercap_1962    2312.888958
gdpPercap_1967    2760.196931
gdpPercap_1972    3313.422188
gdpPercap_1977    3533.003910
gdpPercap_1982    3630.880722
gdpPercap_1987    3738.932735
gdpPercap_1992    2497.437901
gdpPercap_1997    3193.054604
gdpPercap_2002    4604.211737
gdpPercap_2007    5937.029526
Name: Albania, dtype: float64

In [27]:
# print out all the countries, but only the data under the column label "gdpPercap_1952"
print(data.loc[:,"gdpPercap_1952"])

country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487
Name: gdpPercap_1952, dtype: float64

In [28]:
# we could also "ignore country name" and just specify the "column name" and it will
# produce all data under that "column"name.
print (data["gdpPercap_1952"])

country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487
Name: gdpPercap_1952, dtype: float64

In [33]:
# show all "country rows" ...
# uses the colon ":" as the "slice" selection. ("from here to there")
# in this case, its all the rows [:]  
# but... only selecting from the column name "gdpPercap_1952"

print(data.loc[:, "gdpPercap_1952"])

country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487
Name: gdpPercap_1952, dtype: float64

In [38]:
# to print multiple "columns" or multiple "rows" 
# you refer to these by their "label" and put a colon inbetween.
# from here "Italy" to there "Poland" (five countries)
# Note that the selection is "inclusive" at both ends 
# (unlike regular "slice" which is upto but not including)

print(data.loc["Italy":"Poland","gdpPercap_1962":"gdpPercap_1972"])

# as opposed to just one selection
# print(data.loc["Italy","gdpPercap_1962"])

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

In [37]:
# We can chain commands together (like "|" in Bash), here we find the" max" value 
# we use the dot "." 
# the selection is the same , 
# but we add ".max()" at the end,note the call "()"
# and then we close off the print with a ")"

print(data.loc["Italy":"Poland", "gdpPercap_1962":"gdpPercap_1972"].max())

gdpPercap_1962    13450.40151
gdpPercap_1967    16361.87647
gdpPercap_1972    18965.05551
dtype: float64

In [41]:
# Using comparisons to select data based on value

# first get a small set to work with
subset = data.loc["Italy":"Poland", "gdpPercap_1962" : "gdpPercap_1972"]
print("Subset of data:\n" , subset)

# Which values were greater than 10000 ?
print("\nWhere are values large?\n", subset > 10000)

Subset of data:
              gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

Where are values large?
              gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy                 False            True            True
Montenegro            False           False           False
Netherlands            True            True            True
Norway                 True            True            True
Poland                False           False           False

In [4]:
mask = subset >12000
mask

NameError: name 'subset' is not defined